spring.application.name=upf-ride

# PostgreSQL DataSource
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5001/upf_ride?stringtype=unspecified}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:zoubaa}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# JWT
app.jwt.secret=upfRideSecretKey2025SuperSecureKeyForJWTSigning!
app.jwt.expiration=86400000

# CORS - allow React dev server
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000,http://localhost:4200

# Spring Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App config
app.frontend-url=http://localhost:5173

# AI Config (Nvidia NIM / Llama 3.1)
app.ai.nvidia.api-key=${NVIDIA_API_KEY:placeholder}
app.ai.nvidia.base-url=https://integrate.api.nvidia.com/v1
app.ai.nvidia.model=meta/llama-3.1-8b-instruct
